# Generated by Django 2.2.1 on 2019-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='display_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
